version: 2
updates:

  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      maven-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
