// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import java.lang.String;
import java.util.List;

public final class SubscribeNewsletterProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("subscribeNewsletter");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId END_EVENT_MEMBERSHIP_CONFIRMED = new ElementId("endEvent_membershipConfirmed");

    public static final ElementId END_EVENT_MEMBERSHIP_REJECTED = new ElementId("endEvent_membershipRejected");

    public static final ElementId GATEWAY_HAS_EMPTY_SPOTS = new ElementId("gateway_hasEmptySpots");

    public static final ElementId SERVICE_TASK_CLAIM_MEMBERSHIP = new ElementId("serviceTask_claimMembership");

    public static final ElementId SERVICE_TASK_SEND_CONFIRMATION_MAIL = new ElementId("serviceTask_sendConfirmationMail");

    public static final ElementId SERVICE_TASK_SEND_REJECTION_MAIL = new ElementId("serviceTask_sendRejectionMail");

    public static final ElementId SERVICE_TASK_SEND_WELCOME_MAIL = new ElementId("serviceTask_sendWelcomeMail");

    public static final ElementId START_EVENT_SUBMIT_REGISTRATION = new ElementId("startEvent_submitRegistration");

    public static final ElementId USER_TASK_CONFIRM_MEMBERSHIP = new ElementId("userTask_confirmMembership");
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  public static final class Messages {
    public static final MessageName MESSAGE_SUBSCRIPTION_REQUESTED = new MessageName("Message_SubscriptionRequested");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String CLAIM_MEMBERSHIP_DELEGATE = "#{claimMembershipDelegate}";

    public static final String SEND_CONFIRMATION_MAIL_DELEGATE = "#{sendConfirmationMailDelegate}";

    public static final String SEND_REJECTION_MAIL_DELEGATE = "#{sendRejectionMailDelegate}";

    public static final String SEND_WELCOME_MAIL_DELEGATE = "#{sendWelcomeMailDelegate}";
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_CLAIM_MEMBERSHIP_TO_HAS_EMPTY_SPOTS = new BpmnFlow("flow_claimMembershipToHasEmptySpots", null, "serviceTask_claimMembership", "gateway_hasEmptySpots", null, false);

    public static final BpmnFlow FLOW_CONFIRM_MEMBERSHIP_TO_SEND_WELCOME_MAIL = new BpmnFlow("flow_confirmMembershipToSendWelcomeMail", null, "userTask_confirmMembership", "serviceTask_sendWelcomeMail", null, false);

    public static final BpmnFlow FLOW_HAS_EMPTY_SPOTS_TO_SEND_CONFIRMATION_MAIL = new BpmnFlow("flow_hasEmptySpotsToSendConfirmationMail", "Yes", "gateway_hasEmptySpots", "serviceTask_sendConfirmationMail", null, true);

    public static final BpmnFlow FLOW_HAS_EMPTY_SPOTS_TO_SEND_REJECTION_MAIL = new BpmnFlow("flow_hasEmptySpotsToSendRejectionMail", "No", "gateway_hasEmptySpots", "serviceTask_sendRejectionMail", "${!hasEmptySpots}", false);

    public static final BpmnFlow FLOW_SEND_CONFIRMATION_MAIL_TO_CONFIRM_MEMBERSHIP = new BpmnFlow("flow_sendConfirmationMailToConfirmMembership", null, "serviceTask_sendConfirmationMail", "userTask_confirmMembership", null, false);

    public static final BpmnFlow FLOW_SEND_REJECTION_MAIL_TO_MEMBERSHIP_REJECTED = new BpmnFlow("flow_sendRejectionMailToMembershipRejected", null, "serviceTask_sendRejectionMail", "endEvent_membershipRejected", null, false);

    public static final BpmnFlow FLOW_SEND_WELCOME_MAIL_TO_MEMBERSHIP_CONFIRMED = new BpmnFlow("flow_sendWelcomeMailToMembershipConfirmed", null, "serviceTask_sendWelcomeMail", "endEvent_membershipConfirmed", null, false);

    public static final BpmnFlow FLOW_SUBMIT_REGISTRATION_TO_CLAIM_MEMBERSHIP = new BpmnFlow("flow_submitRegistrationToClaimMembership", null, "startEvent_submitRegistration", "serviceTask_claimMembership", null, false);
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations END_EVENT_MEMBERSHIP_CONFIRMED = new BpmnRelations("Membership confirmed", List.of("serviceTask_sendWelcomeMail"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_MEMBERSHIP_REJECTED = new BpmnRelations("Membership rejected", List.of("serviceTask_sendRejectionMail"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations GATEWAY_HAS_EMPTY_SPOTS = new BpmnRelations("Free seat available?", List.of("serviceTask_claimMembership"), List.of("serviceTask_sendConfirmationMail", "serviceTask_sendRejectionMail"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations SERVICE_TASK_CLAIM_MEMBERSHIP = new BpmnRelations("Claim membership", List.of("startEvent_submitRegistration"), List.of("gateway_hasEmptySpots"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_CONFIRMATION_MAIL = new BpmnRelations("Send confirmation mail", List.of("gateway_hasEmptySpots"), List.of("userTask_confirmMembership"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_REJECTION_MAIL = new BpmnRelations("Send rejection mail", List.of("gateway_hasEmptySpots"), List.of("endEvent_membershipRejected"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_WELCOME_MAIL = new BpmnRelations("Send Welcome Mail", List.of("userTask_confirmMembership"), List.of("endEvent_membershipConfirmed"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations START_EVENT_SUBMIT_REGISTRATION = new BpmnRelations("Submit registration form", List.of(), List.of("serviceTask_claimMembership"), null, null, List.of(), "MESSAGE_START_EVENT");

    public static final BpmnRelations USER_TASK_CONFIRM_MEMBERSHIP = new BpmnRelations("Confirm membership", List.of("serviceTask_sendConfirmationMail"), List.of("serviceTask_sendWelcomeMail"), null, null, List.of(), "USER_TASK");
  }
}
