// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.BpmnTimer;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import java.lang.String;
import java.util.List;

public final class SubscribeNewsletterProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("subscribeNewsletter");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId END_EVENT_MAIL_SENT_AGAIN = new ElementId("endEvent_mailSentAgain");

    public static final ElementId END_EVENT_MEMBERSHIP_ACTIVATED = new ElementId("endEvent_membershipActivated");

    public static final ElementId END_EVENT_MEMBERSHIP_CONFIRMED = new ElementId("endEvent_membershipConfirmed");

    public static final ElementId END_EVENT_MEMBERSHIP_DECLINED = new ElementId("endEvent_membershipDeclined");

    public static final ElementId END_EVENT_MEMBERSHIP_REJECTED = new ElementId("endEvent_membershipRejected");

    public static final ElementId EVENT_ABORT_AFTER_3_HALF_DAYS = new ElementId("event_abortAfter3HalfDays");

    public static final ElementId EVENT_CONFIRMATION_REJECTED = new ElementId("event_confirmationRejected");

    public static final ElementId EVENT_RESEND_EVERY_DAY = new ElementId("event_resendEveryDay");

    public static final ElementId GATEWAY_HAS_EMPTY_SPOTS = new ElementId("gateway_hasEmptySpots");

    public static final ElementId GATEWAY_NOTIFY_FORK = new ElementId("gateway_notifyFork");

    public static final ElementId GATEWAY_NOTIFY_JOIN = new ElementId("gateway_notifyJoin");

    public static final ElementId GATEWAY_REVOKE_JOIN = new ElementId("gateway_revokeJoin");

    public static final ElementId SERVICE_TASK_CLAIM_MEMBERSHIP = new ElementId("serviceTask_claimMembership");

    public static final ElementId SERVICE_TASK_NOTIFY_COMMUNITY = new ElementId("serviceTask_notifyCommunity");

    public static final ElementId SERVICE_TASK_RE_SEND_CONFIRMATION_MAIL = new ElementId("serviceTask_reSendConfirmationMail");

    public static final ElementId SERVICE_TASK_REVOKE_CLAIM = new ElementId("serviceTask_revokeClaim");

    public static final ElementId SERVICE_TASK_SEND_CONFIRMATION_MAIL = new ElementId("serviceTask_sendConfirmationMail");

    public static final ElementId SERVICE_TASK_SEND_REJECTION_MAIL = new ElementId("serviceTask_sendRejectionMail");

    public static final ElementId SERVICE_TASK_SEND_WELCOME_MAIL = new ElementId("serviceTask_sendWelcomeMail");

    public static final ElementId START_EVENT_CONFIRMATION_REQUIRED = new ElementId("startEvent_confirmationRequired");

    public static final ElementId START_EVENT_SUBMIT_REGISTRATION = new ElementId("startEvent_submitRegistration");

    public static final ElementId SUB_PROCESS_CONFIRM_MEMBERSHIP = new ElementId("subProcess_confirmMembership");

    public static final ElementId USER_TASK_CONFIRM_MEMBERSHIP = new ElementId("userTask_confirmMembership");
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  public static final class Messages {
    public static final MessageName MESSAGE_CONFIRMATION_REJECTED = new MessageName("Message_ConfirmationRejected");

    public static final MessageName MESSAGE_SUBSCRIPTION_REQUESTED = new MessageName("Message_SubscriptionRequested");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String CLAIM_MEMBERSHIP_DELEGATE = "#{claimMembershipDelegate}";

    public static final String NOTIFY_COMMUNITY_DELEGATE = "#{notifyCommunityDelegate}";

    public static final String RE_SEND_CONFIRMATION_MAIL_DELEGATE = "#{reSendConfirmationMailDelegate}";

    public static final String REVOKE_CLAIM_DELEGATE = "#{revokeClaimDelegate}";

    public static final String SEND_CONFIRMATION_MAIL_DELEGATE = "#{sendConfirmationMailDelegate}";

    public static final String SEND_REJECTION_MAIL_DELEGATE = "#{sendRejectionMailDelegate}";

    public static final String SEND_WELCOME_MAIL_DELEGATE = "#{sendWelcomeMailDelegate}";
  }

  public static final class Timers {
    public static final BpmnTimer EVENT_ABORT_AFTER_3_HALF_DAYS = new BpmnTimer("Duration", "P3DT12H");

    public static final BpmnTimer EVENT_RESEND_EVERY_DAY = new BpmnTimer("Cycle", "R/P1D");
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_ABORT_AFTER_3_HALF_DAYS_TO_REVOKE_CLAIM = new BpmnFlow("flow_abortAfter3HalfDaysToRevokeClaim", null, "event_abortAfter3HalfDays", "gateway_revokeJoin", null, false);

    public static final BpmnFlow FLOW_CLAIM_MEMBERSHIP_TO_HAS_EMPTY_SPOTS = new BpmnFlow("flow_claimMembershipToHasEmptySpots", null, "serviceTask_claimMembership", "gateway_hasEmptySpots", null, false);

    public static final BpmnFlow FLOW_CONFIRM_MEMBERSHIP_TO_MEMBERSHIP_CONFIRMED = new BpmnFlow("flow_confirmMembershipToMembershipConfirmed", null, "userTask_confirmMembership", "endEvent_membershipConfirmed", null, false);

    public static final BpmnFlow FLOW_CONFIRM_MEMBERSHIP_TO_NOTIFY_FORK = new BpmnFlow("flow_confirmMembershipToNotifyFork", null, "subProcess_confirmMembership", "gateway_notifyFork", null, false);

    public static final BpmnFlow FLOW_CONFIRMATION_REJECTED_TO_REVOKE_CLAIM = new BpmnFlow("flow_confirmationRejectedToRevokeClaim", null, "event_confirmationRejected", "gateway_revokeJoin", null, false);

    public static final BpmnFlow FLOW_CONFIRMATION_REQUIRED_TO_SEND_CONFIRMATION_MAIL = new BpmnFlow("flow_confirmationRequiredToSendConfirmationMail", null, "startEvent_confirmationRequired", "serviceTask_sendConfirmationMail", null, false);

    public static final BpmnFlow FLOW_HAS_EMPTY_SPOTS_TO_CONFIRM_MEMBERSHIP = new BpmnFlow("flow_hasEmptySpotsToConfirmMembership", "Yes", "gateway_hasEmptySpots", "subProcess_confirmMembership", null, true);

    public static final BpmnFlow FLOW_HAS_EMPTY_SPOTS_TO_SEND_REJECTION_MAIL = new BpmnFlow("flow_hasEmptySpotsToSendRejectionMail", "No", "gateway_hasEmptySpots", "serviceTask_sendRejectionMail", "${!hasEmptySpots}", false);

    public static final BpmnFlow FLOW_NOTIFY_COMMUNITY_TO_NOTIFY_JOIN = new BpmnFlow("flow_notifyCommunityToNotifyJoin", null, "serviceTask_notifyCommunity", "gateway_notifyJoin", null, false);

    public static final BpmnFlow FLOW_NOTIFY_FORK_TO_NOTIFY_COMMUNITY = new BpmnFlow("flow_notifyForkToNotifyCommunity", null, "gateway_notifyFork", "serviceTask_notifyCommunity", null, false);

    public static final BpmnFlow FLOW_NOTIFY_FORK_TO_SEND_WELCOME_MAIL = new BpmnFlow("flow_notifyForkToSendWelcomeMail", null, "gateway_notifyFork", "serviceTask_sendWelcomeMail", null, false);

    public static final BpmnFlow FLOW_NOTIFY_JOIN_TO_MEMBERSHIP_ACTIVATED = new BpmnFlow("flow_notifyJoinToMembershipActivated", null, "gateway_notifyJoin", "endEvent_membershipActivated", null, false);

    public static final BpmnFlow FLOW_RE_SEND_CONFIRMATION_MAIL_TO_MAIL_SENT_AGAIN = new BpmnFlow("flow_reSendConfirmationMailToMailSentAgain", null, "serviceTask_reSendConfirmationMail", "endEvent_mailSentAgain", null, false);

    public static final BpmnFlow FLOW_RESEND_EVERY_DAY_TO_RE_SEND_CONFIRMATION_MAIL = new BpmnFlow("flow_resendEveryDayToReSendConfirmationMail", null, "event_resendEveryDay", "serviceTask_reSendConfirmationMail", null, false);

    public static final BpmnFlow FLOW_REVOKE_CLAIM_TO_MEMBERSHIP_DECLINED = new BpmnFlow("flow_revokeClaimToMembershipDeclined", null, "serviceTask_revokeClaim", "endEvent_membershipDeclined", null, false);

    public static final BpmnFlow FLOW_REVOKE_JOIN_TO_REVOKE_CLAIM = new BpmnFlow("flow_revokeJoinToRevokeClaim", null, "gateway_revokeJoin", "serviceTask_revokeClaim", null, false);

    public static final BpmnFlow FLOW_SEND_CONFIRMATION_MAIL_TO_CONFIRM_MEMBERSHIP = new BpmnFlow("flow_sendConfirmationMailToConfirmMembership", null, "serviceTask_sendConfirmationMail", "userTask_confirmMembership", null, false);

    public static final BpmnFlow FLOW_SEND_REJECTION_MAIL_TO_MEMBERSHIP_REJECTED = new BpmnFlow("flow_sendRejectionMailToMembershipRejected", null, "serviceTask_sendRejectionMail", "endEvent_membershipRejected", null, false);

    public static final BpmnFlow FLOW_SEND_WELCOME_MAIL_TO_NOTIFY_JOIN = new BpmnFlow("flow_sendWelcomeMailToNotifyJoin", null, "serviceTask_sendWelcomeMail", "gateway_notifyJoin", null, false);

    public static final BpmnFlow FLOW_SUBMIT_REGISTRATION_TO_CLAIM_MEMBERSHIP = new BpmnFlow("flow_submitRegistrationToClaimMembership", null, "startEvent_submitRegistration", "serviceTask_claimMembership", null, false);
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations END_EVENT_MAIL_SENT_AGAIN = new BpmnRelations("Mail sent again", List.of("serviceTask_reSendConfirmationMail"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_MEMBERSHIP_ACTIVATED = new BpmnRelations("Membership activated", List.of("gateway_notifyJoin"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_MEMBERSHIP_CONFIRMED = new BpmnRelations("Membership confirmed", List.of("userTask_confirmMembership"), List.of(), "subProcess_confirmMembership", null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_MEMBERSHIP_DECLINED = new BpmnRelations("Membership declined", List.of("serviceTask_revokeClaim"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_MEMBERSHIP_REJECTED = new BpmnRelations("Membership rejected", List.of("serviceTask_sendRejectionMail"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations EVENT_ABORT_AFTER_3_HALF_DAYS = new BpmnRelations("After 3 1/2 days", List.of(), List.of("gateway_revokeJoin"), null, "subProcess_confirmMembership", List.of(), "TIMER_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_CONFIRMATION_REJECTED = new BpmnRelations("Confirmation rejected", List.of(), List.of("gateway_revokeJoin"), null, "subProcess_confirmMembership", List.of(), "MESSAGE_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_RESEND_EVERY_DAY = new BpmnRelations("Every day", List.of(), List.of("serviceTask_reSendConfirmationMail"), null, "subProcess_confirmMembership", List.of(), "TIMER_BOUNDARY_EVENT");

    public static final BpmnRelations GATEWAY_HAS_EMPTY_SPOTS = new BpmnRelations("Free seat available?", List.of("serviceTask_claimMembership"), List.of("subProcess_confirmMembership", "serviceTask_sendRejectionMail"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations GATEWAY_NOTIFY_FORK = new BpmnRelations(null, List.of("subProcess_confirmMembership"), List.of("serviceTask_sendWelcomeMail", "serviceTask_notifyCommunity"), null, null, List.of(), "PARALLEL_GATEWAY");

    public static final BpmnRelations GATEWAY_NOTIFY_JOIN = new BpmnRelations(null, List.of("serviceTask_sendWelcomeMail", "serviceTask_notifyCommunity"), List.of("endEvent_membershipActivated"), null, null, List.of(), "PARALLEL_GATEWAY");

    public static final BpmnRelations GATEWAY_REVOKE_JOIN = new BpmnRelations(null, List.of("event_confirmationRejected", "event_abortAfter3HalfDays"), List.of("serviceTask_revokeClaim"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations SERVICE_TASK_CLAIM_MEMBERSHIP = new BpmnRelations("Claim membership", List.of("startEvent_submitRegistration"), List.of("gateway_hasEmptySpots"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_NOTIFY_COMMUNITY = new BpmnRelations("Notify community", List.of("gateway_notifyFork"), List.of("gateway_notifyJoin"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_RE_SEND_CONFIRMATION_MAIL = new BpmnRelations("Re-Send confirmation mail", List.of("event_resendEveryDay"), List.of("endEvent_mailSentAgain"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_REVOKE_CLAIM = new BpmnRelations("Revoke claim", List.of("gateway_revokeJoin"), List.of("endEvent_membershipDeclined"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_CONFIRMATION_MAIL = new BpmnRelations("Send confirmation mail", List.of("startEvent_confirmationRequired"), List.of("userTask_confirmMembership"), "subProcess_confirmMembership", null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_REJECTION_MAIL = new BpmnRelations("Send rejection mail", List.of("gateway_hasEmptySpots"), List.of("endEvent_membershipRejected"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_WELCOME_MAIL = new BpmnRelations("Send Welcome Mail", List.of("gateway_notifyFork"), List.of("gateway_notifyJoin"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations START_EVENT_CONFIRMATION_REQUIRED = new BpmnRelations("Confirmation required", List.of(), List.of("serviceTask_sendConfirmationMail"), "subProcess_confirmMembership", null, List.of(), "START_EVENT");

    public static final BpmnRelations START_EVENT_SUBMIT_REGISTRATION = new BpmnRelations("Submit registration form", List.of(), List.of("serviceTask_claimMembership"), null, null, List.of(), "MESSAGE_START_EVENT");

    public static final BpmnRelations SUB_PROCESS_CONFIRM_MEMBERSHIP = new BpmnRelations("Confirm membership", List.of("gateway_hasEmptySpots"), List.of("gateway_notifyFork"), null, null, List.of("event_abortAfter3HalfDays", "event_confirmationRejected", "event_resendEveryDay"), "SUB_PROCESS");

    public static final BpmnRelations USER_TASK_CONFIRM_MEMBERSHIP = new BpmnRelations("Confirm membership", List.of("serviceTask_sendConfirmationMail"), List.of("endEvent_membershipConfirmed"), "subProcess_confirmMembership", null, List.of(), "USER_TASK");
  }
}
